./booksim examples/dragonflyconfig_1
./booksim examples/dragonflyconfig_5
./booksim examples/dragonflyconfig_10
./booksim examples/dragonflyconfig_15
./booksim examples/dragonflyconfig_20
./booksim examples/dragonflyconfig_25
./booksim examples/dragonflyconfig_30
./booksim examples/dragonflyconfig_35
./booksim examples/dragonflyconfig_40
./booksim examples/dragonflyconfig_45
./booksim examples/dragonflyconfig_50
./booksim examples/dragonflyconfig_55
./booksim examples/dragonflyconfig_60
./booksim examples/dragonflyconfig_65
./booksim examples/dragonflyconfig_70
./booksim examples/dragonflyconfig_75
./booksim examples/dragonflyconfig_80
./booksim examples/dragonflyconfig_85
./booksim examples/dragonflyconfig_90
